FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04

# Install Python, git and other build tools
RUN apt update && apt install -y \
    curl \
    git

# Clone SageAttention
RUN git clone https://github.com/thu-ml/SageAttention.git
WORKDIR /SageAttention

# Install uv python manager
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

# Install python
RUN uv python install 3.12

# Create python venv
RUN uv venv -p 3.12

# Upgrade pip / setuptools / wheel
RUN uv pip install --upgrade pip setuptools wheel packaging triton

# Install PyTorch for CUDA 12.9
RUN uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu129

# Configure GPU support
ENV TORCH_CUDA_ARCH_LIST="8.9;8.6"

# Install SageAttention
RUN uv run setup.py bdist_wheel

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]